# Generated by Django 5.2.11 on 2026-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('languages_used', models.TextField()),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
    ]
